import streamlit as st
import requests

# -------------- BASIC PAGE SETUP --------------
st.set_page_config(page_title="FraudShield – Website Risk Tester", layout="centered")

st.title("FraudShield – Website Risk Evaluation")
st.write("Enter any website URL below to see its risk assessment based on the FraudShield model.")

# -------------- INPUT --------------
url = st.text_input("Website URL", placeholder="https://example.com")

if st.button("Check Website"):
    if not url:
        st.warning("Please enter a URL first.")
    else:
        try:
            # Call your existing Render API
            api_url = "https://website-risk-scorer-api.onrender.com/scan_url"
            resp = requests.post(api_url, json={"url": url}, timeout=15)

            if not resp.ok:
                st.error("The risk evaluation server returned an error.")
            else:
                data = resp.json()

                # Expected fields (based on your extension)
                risk_class = data.get("risk_class", "Unknown")
                risk_score = data.get("risk_score", 0)
                blacklist_flag = data.get("blacklist_flag", 0)

                # Choose a color
                color = "#4CAF50"  # default safe green
                if risk_class == "Low Risk":
                    color = "#FFC107"
                elif risk_class == "Suspicious":
                    color = "#FF9800"
                elif risk_class == "High Risk":
                    color = "#F44336"
                if blacklist_flag == 1:
                    color = "#B71C1C"

                # Show result nicely
                st.markdown(
                    f"""
                    <div style="padding:16px;border-radius:10px;background-color:{color};color:white;text-align:center;">
                        <h3 style="margin:0;">{risk_class}</h3>
                        <p style="margin:4px 0;"><strong>Risk Score:</strong> {float(risk_score):.2f}%</p>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                if blacklist_flag == 1:
                    st.error("☠ This website is flagged as a known dangerous threat.")
                else:
                    st.info("Result generated by the FraudShield backend risk model.")

        except Exception as e:
            st.error("Could not connect to the risk evaluation server.")
            st.write(e)
