import streamlit as st

# ---------------------------------------------------------
# PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="FraudShield Dashboard",
    layout="wide"
)

# ---------------------------------------------------------
# OPTIONAL LOGO (remove if no logo available)
# ---------------------------------------------------------
st.markdown(
    """
    <div style="text-align:center; margin-top:20px;">
        <img src="https://i.imgur.com/wQK3O0M.png" width="140">
    </div>
    """,
    unsafe_allow_html=True
)

# ---------------------------------------------------------
# TITLE & INTRODUCTION
# ---------------------------------------------------------
st.markdown("<h1 style='text-align:center;'>🛡️ FraudShield – AI-Powered Website Risk Evaluation</h1>", unsafe_allow_html=True)

st.write(
    """
FraudShield is an AI-driven fraud detection system designed to evaluate online shopping websites 
and identify potentially deceptive, dangerous, or fraudulent environments in real time.  

This dashboard demonstrates:
- How the system analyzes websites  
- How risk scores are generated  
- How external users (like FindMe LLC) can integrate the API  
- The model's performance, intelligence, and trust indicators  
- A fully functional UI for real-time scanning  

Use the left navigation menu to explore each capability.
"""
)

st.markdown("---")

# ---------------------------------------------------------
# PRODUCT OVERVIEW SECTION
# ---------------------------------------------------------
st.header("📌 What You Can Do in This Dashboard")

col1, col2 = st.columns(2)

with col1:
    st.subheader("🔍 Website Scanner")
    st.write(
        "Test any URL and instantly receive a fraud-risk score, classification, "
        "and downloadable PDF report generated by the FraudShield API."
    )

    st.subheader("🧠 Model Intelligence")
    st.write(
        "Review ML performance metrics, feature importance, and a simplified breakdown "
        "of how the fraud detection model works."
    )

    st.subheader("🔌 API Explorer")
    st.write(
        "Try the FraudShield API directly, view live JSON output, and copy integration-ready "
        "code snippets (Python, JavaScript, cURL)."
    )

with col2:
    st.subheader("📊 Reports & Logs")
    st.write(
        "View your session’s scan history and export logs for demos, documentation, "
        "or integration testing."
    )

    st.subheader("🌐 Real-World Use Cases")
    st.write(
        """
        - Protect platform users when they follow external links  
        - Filter risky online stores before transactions  
        - Integrate risk signals into onboarding or verification workflows  
        - Evaluate suspicious online marketplaces, portfolios, or booking pages  
        """
    )

st.markdown("---")

# ---------------------------------------------------------
# ABOUT / PURPOSE SECTION
# ---------------------------------------------------------
st.header("🎯 Why FraudShield Matters")

st.write(
    """
Online shopping fraud is one of the fastest-growing cybercrimes in the United States, 
causing billions in losses and affecting millions of consumers.  

FraudShield provides:
- Real-time fraud prevention  
- Scalable nation-wide protection  
- API-based integration for businesses  
- Evidence-based ML scoring  
- Consumer safety insights aligned with U.S. cybersecurity priorities  

This dashboard serves as a **live demonstration** of the system’s capabilities for stakeholders, 
research partners, commercial collaborators, and USCIS review purposes.
"""
)

st.markdown("---")

# ---------------------------------------------------------
# FOOTER
# ---------------------------------------------------------
st.write(
    """
    <p style="text-align:center; font-size:13px; color:gray;">
    FraudShield — Real-time fraud detection for safer online interactions.
    </p>
    """,
    unsafe_allow_html=True
)
